unpackaged/main/default/objects/Contact/fields/Family_Group__c.field-meta.xml
<CustomField>
    <fullName>Family_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CARE Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Number_of_Family_Members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Family_Members__c</fullName>
    <label>Number of Family Members</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <label>Principal Applicant or Family Member</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Applicant</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Derivative - Child</fullName>
            </value>
            <value>
                <fullName>Derivative - Spouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <label>Mission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/Traveler__c.object-meta.xml
<CustomObject>
    <label>Traveler</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Traveler Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/fields/Family_Group__c.field-meta.xml
<CustomField>
    <fullName>Family_Group__c</fullName>
    <formula>Traveler__r.Family_Group__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CARE Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <description>Master-Detail to the mission that the traveler is on</description>
    <label>Mission</label>
    <referenceTo>Mission__c</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Number_of_Family_Members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Family_Members__c</fullName>
    <formula>Traveler__r.Number_of_Family_Members__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Family Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <formula>TEXT(Traveler__r.Principal_Applicant_or_Family_Member__c)</formula>
    <label>Principal Applicant or Family Member</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The principal applicant that the traveler is related to</description>
    <label>Related To</label>
    <referenceTo>Traveler__c</referenceTo>
    <relationshipLabel>Principal Applicant</relationshipLabel>
    <relationshipName>Related</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Traveler__c.field-meta.xml
<CustomField>
    <fullName>Traveler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Traveler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/RelationshipAssigner.cls
public with sharing class RelationshipAssigner {

    public class FlowInputs {
        @InvocableVariable public String missionId;
    }

    @InvocableMethod(label='Assign Relationships')
    public static void assignRelationships(List<FlowInputs> inputs) {
        List<Traveler__c> travelers = new List<Traveler__c>();
        if(inputs.size() > 0 && inputs[0].missionId != null){
            travelers = [SELECT Id, Traveler__r.Number_of_Family_Members__c, Mission__c, Related_To__c, Family_Group__c, Principal_Applicant_or_Family_Member__c,
                        Number_of_Family_Members__c FROM Traveler__c WHERE Mission__c =: inputs[0].missionId];
        } else {
            return;
        }
        
        Map<String, Traveler__c> principalApplicants = new Map<String, Traveler__c>();
        Map<String, List<Traveler__c>> familyMembers = new Map<String, List<Traveler__c>>();
        
        String familyGroup;
        String app;
        for(Traveler__c con : travelers){
            familyGroup = con.Family_Group__c;
            app = con.Principal_Applicant_or_Family_Member__c;
            if(app == 'Principal Applicant'){
                if(!principalApplicants.containsKey(familyGroup)){
                    principalApplicants.put(familyGroup, con);
                }
            } else if(app != '' && app != null){
                if(!familyMembers.containsKey(familyGroup)){
                    List<Traveler__c> familyGroupList = new List<Traveler__c>();
                    familyGroupList.add(con);
                    familyMembers.put(familyGroup, familyGroupList);
                } else {
                    familyMembers.get(familyGroup).add(con);
                }
            } 
        }

        List<Traveler__c> toUpdate = new List<Traveler__c>();
        List<Contact> toUpdateCon = new List<Contact>();
        for(String groupNum : principalApplicants.keySet()){
            if(familyMembers.containsKey(groupNum)){
                Traveler__c principal = principalApplicants.get(groupNum);
                List<Traveler__c> family = familyMembers.get(groupNum);
                for(Traveler__c member : family){
                    if(member.Related_To__c != principal.Id){
                        member.Related_To__c = principal.Id;
                        Contact con = member.Traveler__r;
                        con.Number_of_Family_Members__c = family.size();
                        toUpdate.add(member);
                        toUpdateCon.add(con);
                    }
                }
                Contact con = principal.Traveler__r;
                con.Number_of_Family_Members__c = family.size();
                toUpdateCon.add(con);
            }
        }

        if(!toUpdate.isEmpty()){
            update toUpdate;
        }
        if(!toUpdateCon.isEmpty()){
            update toUpdateCon;
        }
        
    }
}