unpackaged/main/default/objects/Contact/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <label>Principal Applicant or Family Member</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Applicant</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Derivative - Child</fullName>
            </value>
            <value>
                <fullName>Derivative - Spouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Passport Photo</fullName>
            </value>
            <value>
                <fullName>Entry Stamp</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Exit Permit</fullName>
            </value>
            <value>
                <fullName>Tazkira</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Lodging COR Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <label>Mission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/Traveler__c.object-meta.xml
<CustomObject>
    <label>Traveler</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Traveler Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <description>Master-Detail to the mission that the traveler is on</description>
    <label>Mission</label>
    <referenceTo>Mission__c</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <formula>TEXT(Traveler__r.Principal_Applicant_or_Family_Member__c)</formula>
    <label>Principal Applicant or Family Member</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Traveler__c.field-meta.xml
<CustomField>
    <fullName>Traveler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Traveler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TravelerImagesControllerTest.cls
@isTest
private class TravelerImagesControllerTest {
    
    @TestSetup
    static void makeData(){
        Mission__c mission = new Mission__c(Name = 'Test Mission');
        insert mission;

        Account testAcc = new Account(Name = 'Testing Account');
        insert testAcc;
        

        Contact con = new Contact(AccountId = testAcc.Id, LastName = 'Test', Mission__c = mission.Name);
        con.Principal_Applicant_or_Family_Member__c = 'Principal Applicant';
        insert con; 

        ContentVersion contentVersion = new ContentVersion(Title = '', PathOnClient = 'Pic.jpg', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true,Document_Type__c ='Passport');
        insert contentVersion; 
        List<ContentDocument> documents = [SELECT Id, Title FROM ContentDocument];

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = con.id;
        cdl.ContentDocumentId = documents[0].Id;
        insert cdl;
    }

    @isTest 
    private static void testImagesController(){
        Traveler__c traveler = [SELECT Id, Traveler__c, Mission__c FROM Traveler__c WHERE Mission__r.Name =: 'Test Mission' LIMIT 1];

        String contentDetails = TravelerImagesController.getContentDetails(traveler.Id);

        System.debug(contentDetails);
    }

}