unpackaged/main/default/objects/Contact/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mission Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <label>Principal Applicant or Family Member</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Applicant</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Derivative - Child</fullName>
            </value>
            <value>
                <fullName>Derivative - Spouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <label>Mission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/Traveler__c.object-meta.xml
<CustomObject>
    <label>Traveler</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Traveler Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Traveler__c/fields/Covid_19_Result__c.field-meta.xml
<CustomField>
    <fullName>Covid_19_Result__c</fullName>
    <description>The traveler&#39;s covid-19 test results</description>
    <label>Covid-19 Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Test not taken</fullName>
                <default>true</default>
                <label>Test not taken</label>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Awaiting Result</fullName>
            </value>
            <value>
                <fullName>Family Member Positive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <description>Master-Detail to the mission that the traveler is on</description>
    <label>Mission</label>
    <referenceTo>Mission__c</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Principal_Applicant_or_Family_Member__c.field-meta.xml
<CustomField>
    <fullName>Principal_Applicant_or_Family_Member__c</fullName>
    <formula>TEXT(Traveler__r.Principal_Applicant_or_Family_Member__c)</formula>
    <label>Principal Applicant or Family Member</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Relocation_Status__c.field-meta.xml
<CustomField>
    <fullName>Relocation_Status__c</fullName>
    <label>Relocation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No contact made</fullName>
            </value>
            <value>
                <fullName>Initial contact made</fullName>
            </value>
            <value>
                <fullName>Pick Up Details Confirmed</fullName>
            </value>
            <value>
                <fullName>Logged onto the bus</fullName>
            </value>
            <value>
                <fullName>Initial Biometric Capture</fullName>
            </value>
            <value>
                <fullName>Complete biometrics captured</fullName>
            </value>
            <value>
                <fullName>Successful Border Crossing</fullName>
            </value>
            <value>
                <fullName>Arrived at Third Country</fullName>
            </value>
            <value>
                <fullName>Passport Collected</fullName>
            </value>
            <value>
                <fullName>Passport Delivered to Qatar Embassy</fullName>
            </value>
            <value>
                <fullName>Passport Returned from Embassy</fullName>
            </value>
            <value>
                <fullName>Qatar Visa Received</fullName>
            </value>
            <value>
                <fullName>Pakistan Entry Stamp Received</fullName>
            </value>
            <value>
                <fullName>Pakistan Visa Received</fullName>
            </value>
            <value>
                <fullName>Pakistan Exit Visa Applied For</fullName>
            </value>
            <value>
                <fullName>Pakistan Exit Visa Received</fullName>
            </value>
            <value>
                <fullName>Covid Test Received</fullName>
            </value>
            <value>
                <fullName>Airline Ticket Issued</fullName>
            </value>
            <value>
                <fullName>Passport &amp; Documents Collected from SEPAR</fullName>
            </value>
            <value>
                <fullName>Arrived at the Airport</fullName>
            </value>
            <value>
                <fullName>Ticket Provided to Passenger</fullName>
            </value>
            <value>
                <fullName>Qatar Visa Collected</fullName>
            </value>
            <value>
                <fullName>Cleared Immigration</fullName>
            </value>
            <value>
                <fullName>Arrived at Border</fullName>
            </value>
            <value>
                <fullName>Ticketed</fullName>
            </value>
            <value>
                <fullName>Boarded Plane</fullName>
            </value>
            <value>
                <fullName>Arrival in the RRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Traveler__c/fields/Traveler__c.field-meta.xml
<CustomField>
    <fullName>Traveler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Traveler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Travelers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/RelationshipAssignerTest.cls
@isTest
private class RelationshipAssignerTest {
   
    @TestSetup
    static void makeData(){
        Mission__c mission = new Mission__c(Name = 'Test Mission');
        insert mission;

        Account testAcc = new Account(Name = 'Testing Account');
        insert testAcc;
        
        

        
        Contact principal = new Contact(AccountId = testAcc.Id, LastName = 'Test', Mission__c = mission.Name);
        principal.Principal_Applicant_or_Family_Member__c = 'Principal Applicant';
        Contact familyMember1 = new Contact(AccountId = testAcc.Id, LastName = 'Test', Mission__c = mission.Name);
        familyMember1.Principal_Applicant_or_Family_Member__c = 'Family Member';
        Contact familyMember2 = new Contact(AccountId = testAcc.Id, LastName = 'Test', Mission__c = mission.Name);
        familyMember2.Principal_Applicant_or_Family_Member__c = 'Family Member';
        insert new List<Contact>{principal, familyMember1, familyMember2};

        Traveler__c duplicate = new Traveler__c(Traveler__c = principal.Id, Mission__c = mission.Id);
        try {
            insert duplicate;
        } catch (Exception ex){
            System.debug('Duplicate caught');
        }
    }

    @isTest 
    private static void testRelationshipAssigner(){
        Mission__c mission = [SELECT Id, Name FROM Mission__c WHERE Name =: 'Test Mission'];
        RelationshipAssigner.FlowInputs flowInput = new RelationshipAssigner.FlowInputs();
        flowInput.missionId = mission.Id;
        
        RelationshipAssigner.assignRelationships(new List<RelationshipAssigner.FlowInputs>{flowInput});

        RelationshipAssigner.assignRelationships(new List<RelationshipAssigner.FlowInputs>());
    }

    @isTest
    private static void testTravelerUpdates(){
        Traveler__c traveler = [SELECT Id, Name, Principal_Applicant_or_Family_Member__c, Relocation_Status__c, Covid_19_Result__c FROM Traveler__c 
                                WHERE Principal_Applicant_or_Family_Member__c =: 'Principal Applicant'];

        Test.startTest();
        traveler.Relocation_Status__c = 'Ticketed';
        update traveler;

        traveler.Covid_19_Result__c = 'Positive';
        update traveler;

        Test.stopTest();

        List<Traveler__c> family = [SELECT Id, Name, Principal_Applicant_or_Family_Member__c, Relocation_Status__c, Covid_19_Result__c FROM Traveler__c 
                                    WHERE Principal_Applicant_or_Family_Member__c =: 'Family Member'];
        System.debug(family);

        for(Traveler__c member : family){
            System.assertEquals(member.Relocation_Status__c, 'Ticketed');
            System.assertEquals(member.Covid_19_Result__c, 'Family Member Positive');
        }
    }
}